# Generated by Django 2.2.8 on 2021-01-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0002_auto_20210121_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment_count',
        ),
    ]
