# Generated by Django 2.2.8 on 2022-03-08 12:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0006_auto_20220222_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='richcontent',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='detail_content',
            field=tinymce.models.HTMLField(default='short description', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
