# Generated by Django 2.2.8 on 2022-03-11 12:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0007_auto_20220308_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='detail_content',
        ),
        migrations.AddField(
            model_name='blog',
            name='richcontent',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
