# Generated by Django 2.2.8 on 2022-03-18 10:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0008_auto_20220311_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='richcontent',
        ),
        migrations.AddField(
            model_name='blog',
            name='detail_content',
            field=tinymce.models.HTMLField(default='more details', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
