# Generated by Django 2.2.8 on 2021-01-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210123_1427'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='jobpost',
        #     old_name='title',
        #     new_name='job_title',
        # ),
        
        migrations.RenameField(
            model_name='jobpost',
            old_name='jobadmin_name',
            new_name='job_admin_name',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='detail',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='title',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='image',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='locations',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements',
            field=models.TextField(default=None),
        ),
    ]
