# Generated by Django 2.2.8 on 2021-01-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210123_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
