# Generated by Django 2.2.8 on 2021-01-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210123_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='application_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='country',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
