# Generated by Django 3.2.12 on 2022-02-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20220219_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='application_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
