# Generated by Django 3.2.12 on 2022-02-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_jobs_application_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='application_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
