# Generated by Django 3.2.12 on 2022-02-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_jobs_application_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='salary',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='gender',
            field=models.BooleanField(choices=[(None, 'Any'), (True, 'male'), (False, 'female')], null=True),
        ),
    ]
