# Generated by Django 2.2.8 on 2021-03-08 18:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0002_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='DService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=300)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('service_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('featured_services', models.BooleanField(default=False)),
                ('service_image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
    ]
