# Generated by Django 2.2.8 on 2022-02-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_dservice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dservice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
