# Generated by Django 3.2.12 on 2022-03-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20220222_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dservice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
