# Generated by Django 2.2.8 on 2022-03-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
