# Generated by Django 2.2.8 on 2022-03-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_visa_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='image',
        ),
    ]
