# Generated by Django 2.2.8 on 2022-03-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_remove_visa_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
